sudo: false
language: python
python:
#  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"
#  - "3.7"
#  - "3.8"
  - "3.9"
install: 
  - pip install tox-travis
  - version="1.0.1"
  - echo "$TRAVIS_TAG"
  - TRAVIS_TAG="v$version"
  - echo "$TRAVIS_COMMIT"
  - echo "$TRAVIS_BUILD_NUMBER"
  - git tag $TRAVIS_TAG $TRAVIS_COMMIT
  - export RELEASE_PKG_FILE="dist/interfax-$version.zip"
script: tox
before_deploy:
  - python setup.py sdist --formats=zip -k
  - find ./dist -iname "*.zip" -print0 | xargs -0 pip install
deploy:
  provider: releases
  api_key:
    secure: Vse55dOh5gTG3rdln2uIWlt0jEGyPVRvPWDmElNoGv7+Fjl3023PWCC5yQrgvYQRwWExVA28d85TPBWlfyiJLFseSoWtc0O6/tKWI9r9+eeArNqAxZkFpa167a4aiulLaHhYi6y3aVWW+kpE49nOEb6J4G1aGcqRVAPLb/WP9mz4jVVESmGsqpYoOLbAZ5ShZ2D5kIdosR4vTjcl4u2TxQfr5IUikW05aEfd7ib/Rx08pylTG8ShZKJpczNcmOejrVR6vmt/fNzxBtE1QvHKDD9EWrLKZyb1v6mhI8W5bwOKlHN2UrfEFCi8CSQYIAeM8OexwWUMyPeKScaIuxc5orsn9eDyOy5ItGKMg0GDmRx+GI+tUnoA2VAMOOW5vFJFOMi1AkcEJkoqXzMbWIesj8hDyg87HznUZn0lJzPuww1IJss/KH3xcUKqpJGomYPXBwFVj5mjIg0ErTKgTyJvq8eYnZWDUIW+RLlh6dCrE4lDXtLgwfhwmcFyCgn8qAZKggrrlWHBiL6ZAE2bewIVV9M2T5dvJbe8eB4SR/UumEOQn/giCZhCl6qxt1UyzJhOcewcnGUz4jyf68AF9Jm0kUxI+2PI4WeldI7JnEHK1rEI/cRzTV3Izd/KfdDaBz+Wgpva+21OXiMvB3u1hSG8te+F2pFO0cjeoQg3zMhpdDE=
  file: ${RELEASE_PKG_FILE}
  skip_cleanup: true
  provider: pypi
  server: https://test.pypi.org/legacy/ # Remove for deployment to official PyPi repo
  username: "__token__"
  password:
    secure: XrBrHda//juXXlpZLnFp2EQf//53oh2FbcyncL5Yyqq7J2cDZzqRaP4k2ztUPNN7Kg7r44oJCzKgpEbFzt1s5oiJJtF1Vk0UImpkKfnQ2A1NPS0Tyh3zBJelaDdM2Oo09+wLBTd56F5ysdUTfcIQYiWc509oumjZG/flSJYmYv+U90WNnxwraKl9XGkJAL1Rxw2RrAa7VSNRzGq0BcWSV3wRxV9QYLWLN4ojjMQtho5t8HAW+oRXTqlehsbNR6x93yWxNAhLwrOuga/J2ZsaHzJ98YN8yK2oQwcAP6foD0ESr3p8q8m3WNWBGKZez5KPXRg9U4M9AqwVQDiptLOr6RS1V0avUl+EHWv8SIKPvGLJNOA9x/ks9TJKoLhol+Flfb6eu2MPrUQE324xaCNyNLpKwFD5kHTAvn5++FXgXzT+/7h2ONfoPJXpaMOuJMw9supmmNEck8L5xgsQgLtLcLOQRwrSNv1q1o9RqqKEpqiwG8ipFAt2VQFqq2uYbgJxhTv8NVkW0VPm9yyXeMqDT3rQAUD39FsVoUVUJ+aTsMOG95R1Vhrf/zsNEQiSPUHRvrZic0TlcD4D4LLMCF552jgjC9tmda6ItEBoShsA3OETTXpj2CeE69Xka/HVLJW4w0A+r+aLZzQKmzKG665bTzczkmeaKDD01vt4/YtsJtY=
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION == 3.9
    repo: ricky-shake-n-bake-bobby/interfax-python
