sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install: pip install tox-travis
script: tox
before_deploy:
#- TRAVIS_TAG=v1.0.2
- echo "$TRAVIS_TAG" 
- echo "$TRAVIS_COMMIT"
- echo "$TRAVIS_BUILD_NUMBER"
- git tag $TRAVIS_TAG $TRAVIS_COMMIT
- python setup.py sdist --formats=zip -k
- find ./dist -iname "*.zip" -print0 | xargs -0 pip install
deploy:
  provider: releases
  api_key:
    secure: KVhL8ogtB+g2yZTBDcaz6TpLofwg7AROXdq9wzyDbxDUmQGWe7k95s+jZlyPBEXXxzbQ6+vGhsOIE4QDgIlDCAlLGXzbN8pQ+KJbp9WXrJsvtTuJk87yV2ayntcYhrTbIs4qsKoZ9bs/cRqZVu+yNlsEQ7lJYiIVDmR7IpZg8nQw7xvMy6oh3bU+LH8lGHOH0ZiWkOK1cOM+ciLIUydzu+Hn5JBvTRmuR22QY4fTSjOj3baElWLGnzIebFGtQdlgmteYHupbhTzqtfORgVfZy+EIXy9giZk/mCy+NQ3TV90w2OznX4qBXj+rtl+Eif0CY5a0pc8aZLf/3FMDo7e9MD4lwqypUOKCdkxAeDmohhZYGJA3yBTlqi7seEXYLIoJwi84vK4EMSS2nvaa7vqwimX3vLe923jcU6/d2kHqijCDlYhf8GZOlJhFmTdDI6AqOujMiH6ftphCxtw+5BepYSRj/ncFHrDLNbBAqnOS5EBJx35ihgLXOQks0lOZxHffYVetr2qzrU/5yisufuc90XMXy+sQ8mRd3Q+tO/JlweVGFcD1oEKi3Gz6ZmFBmsoI/4TJ0njY5GDCIPEzp4PECGAYN/U9qdSw3eHNzUPJfDuzfW5QAV6LAf3hUq2poQkXUXeIK0s7SA3h/PefWoSMfTudq0l53+RW0/JnFEBLeys=
  file: ${RELEASE_PKG_FILE}
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION == 3.9
    repo: ricky-shake-n-bake-bobby/interfax-python
