sudo: false
language: python
python:
#  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"
#  - "3.7"
#  - "3.8"
  - "3.9"
install: pip install tox-travis
script: tox
before_deploy:
  - TRAVIS_TAG=v1.0.2
  - echo "$TRAVIS_TAG" 
  - echo "$TRAVIS_COMMIT"
  - echo "$TRAVIS_BUILD_NUMBER"
  - git tag $TRAVIS_TAG $TRAVIS_COMMIT
  - python setup.py sdist --formats=zip -k
  - find ./dist -iname "*.zip" -print0 | xargs -0 pip install
deploy:
  provider: releases
  api_key:
    secure: eOU9udkkFEgkhY9V12f0lFAw8JyT53S5h56PbGmCkcRf4Pb46D8NwUDbfJEUa5GqyfVxb9V453PC7YmMSJe1XTgvgG85TOkNPu9Q3tVT38rFyCS/+tlNQIELBriYzBr1ymkVv73BWbhB5U+LQa+jvK5J3joIlMz2UTZlIeRP7BgyYj0sbSy8z7g15wYutig3TEEjRe8YvG6bWki2UDF0QJan4nuY1Ru1fYaEBNyzIfKCMZaNDZ4KWhzv9WfFeiFTQeXfvUsqvO0YNa64JiB0/XR2EdFoyo6dXKo8NoiJaG5TaFI4RkVfRgNSczaB9qZ6iECH2cJO2G22QMFhzEDesy/MTbBpkOcnPio0f7Ok9sMQ6qB+gArpXR+cg5RZxYZnvS8T8dsNQVS+9Hy9wpcuxgBTuvb+w49KvyaebOmp2zrmGkO+xlZWaHo86Tm8FgeZndHNWjax4pyeZ7hrPUEBD0lBHXqqJrQZKKraL+WEw3ENiIOcksLOCxZQrTLMUVkG6YR7oFqfjpdgIW/Nd2NnCJhg6emepxp6RnI4skxyJAuwzffrptDBy+CQbBbfiIwEExB1Bv228zSEEDkxvinBm01e6oMvJ5iHKyzubvzz+2cykw5LwY6bmQpDifjsleO7MOZCogXeUFiblY+ncWwB9dOExhbpGu37i+4QZxvjWnQ=
  file: ${RELEASE_PKG_FILE}
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION == 3.9
    repo: ricky-shake-n-bake-bobby/interfax-python
