sudo: false
language: python
python:
#  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"
#  - "3.7"
#  - "3.8"
  - "3.9"
install: 
  - pip install tox-travis
  - version="1.0.1"
  - echo "$TRAVIS_TAG"
  - TRAVIS_TAG="v$version"
  - echo "$TRAVIS_COMMIT"
  - echo "$TRAVIS_BUILD_NUMBER"
  - git tag $TRAVIS_TAG $TRAVIS_COMMIT
  - echo "interfax-$version.zip"
  - export RELEASE_PKG_FILE=".dist/interfax-$version.zip"
script: tox
before_deploy:
  - python setup.py sdist --formats=zip -k
  - find ./dist -iname "*.zip" -print0 | xargs -0 pip install
deploy:
  provider: releases
  api_key:
    secure: Vse55dOh5gTG3rdln2uIWlt0jEGyPVRvPWDmElNoGv7+Fjl3023PWCC5yQrgvYQRwWExVA28d85TPBWlfyiJLFseSoWtc0O6/tKWI9r9+eeArNqAxZkFpa167a4aiulLaHhYi6y3aVWW+kpE49nOEb6J4G1aGcqRVAPLb/WP9mz4jVVESmGsqpYoOLbAZ5ShZ2D5kIdosR4vTjcl4u2TxQfr5IUikW05aEfd7ib/Rx08pylTG8ShZKJpczNcmOejrVR6vmt/fNzxBtE1QvHKDD9EWrLKZyb1v6mhI8W5bwOKlHN2UrfEFCi8CSQYIAeM8OexwWUMyPeKScaIuxc5orsn9eDyOy5ItGKMg0GDmRx+GI+tUnoA2VAMOOW5vFJFOMi1AkcEJkoqXzMbWIesj8hDyg87HznUZn0lJzPuww1IJss/KH3xcUKqpJGomYPXBwFVj5mjIg0ErTKgTyJvq8eYnZWDUIW+RLlh6dCrE4lDXtLgwfhwmcFyCgn8qAZKggrrlWHBiL6ZAE2bewIVV9M2T5dvJbe8eB4SR/UumEOQn/giCZhCl6qxt1UyzJhOcewcnGUz4jyf68AF9Jm0kUxI+2PI4WeldI7JnEHK1rEI/cRzTV3Izd/KfdDaBz+Wgpva+21OXiMvB3u1hSG8te+F2pFO0cjeoQg3zMhpdDE=
  file: ${RELEASE_PKG_FILE}
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION == 3.9
    repo: ricky-shake-n-bake-bobby/interfax-python
